require('dotenv').config();
const mongoose = require('mongoose');
const Cafe = require('./models/Cafe');
const { resolveStoredImageUrl } = require('./config/imageStorage');

const cafes = [
  {
    name: "Goodfields Makassar",
    description: "Cafe aesthetic real dari link Google Maps yang kamu kirim. Cocok untuk nongkrong santai dengan interior modern dan suasana nyaman di area Ujung Pandang.",
    address: "Jalan Chairil Anwar, Sawerigading, Ujung Pandang, Makassar",
    category: "aesthetic",
    rating: 4.7,
    priceRange: "$$",
    facilities: ["WiFi", "AC", "Smoking Area", "Meeting Room", "Live Music"],
    openHours: "09:00 - 24:00",
    image: "/goodfields-makassar.png",
    mapsLink: "https://maps.app.goo.gl/j6uMYGuWDQusQmhL9",
    location: { lat: -5.1395574, lng: 119.4107145 }
  },
  {
    name: "Duft Coffee Indonesia",
    description: "Cafe real dari link Google Maps yang kamu kirim. Vibenya hangat dengan dominasi kayu, cocok untuk nongkrong santai dan ngopi di area Panakkukang.",
    address: "Jalan A.P. Pettarani, Tamamaung, Panakkukang, Makassar",
    category: "aesthetic",
    rating: 4.8,
    priceRange: "$$",
    facilities: ["WiFi", "AC", "Coffee Bar", "Indoor Seating", "Parking"],
    openHours: "10:00 - 01:00",
    image: "/duft-coffee-indonesia.png",
    mapsLink: "https://maps.app.goo.gl/QGPTcSpqvfukdRhz6",
    location: { lat: -5.1479834, lng: 119.4385163 }
  },
  {
    name: "Postropis Coffee & Space",
    description: "Cafe real dari link Google Maps yang kamu kirim. Tempatnya luas, modern, dan cocok untuk kerja, meeting, atau nongkrong di area Panakkukang.",
    address: "Jalan Adipura Raya, Karuwisi Utara, Panakkukang, Makassar",
    category: "coworking",
    rating: 4.8,
    priceRange: "$$",
    facilities: ["WiFi Cepat", "AC", "Meeting Room", "Workspace", "Parking"],
    openHours: "07:00 - 23:00",
    image: "/postropis-coffee-space.png",
    mapsLink: "https://maps.app.goo.gl/z1m3AJjDsM5HotvXA",
    location: { lat: -5.1329919, lng: 119.4332702 }
  },
  {
    name: "1997 Coffee",
    description: "Cafe real dari link Google Maps yang kamu kirim. Interior clean minimalis dengan nuansa abu-abu modern, cocok buat nongkrong santai dan foto aesthetic di area Panakkukang.",
    address: "Jalan Bougenville, Masale, Panakkukang, Makassar",
    category: "aesthetic",
    rating: 5.0,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/1997-coffee.png",
    mapsLink: "https://maps.app.goo.gl/qxGm2D5hxpji4ZNE7",
    location: { lat: -5.1584325, lng: 119.4447899 }
  },
  {
    name: "EIGHTEEN Eatery",
    description: "Cafe real dari link Google Maps yang kamu kirim. Interior warm dan clean dengan sentuhan kayu, cocok untuk nongkrong, makan, dan foto aesthetic di area Maricaya.",
    address: "Jalan Rusa, Maricaya, Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Dining Area", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/eighteen-eatery.png",
    mapsLink: "https://maps.app.goo.gl/1Tox751B86ugr9SPA",
    location: { lat: -5.15163, lng: 119.4216345 }
  },
  {
    name: "Mark Trees Cafe",
    description: "Cafe hangat dengan dominasi interior kayu yang memberikan kesan nyaman dan homey, cocok untuk bersantai, mengobrol, atau menikmati kopi.",
    about: "Mark Trees Cafe menawarkan suasana hangat dengan dominasi interior kayu yang memberikan kesan nyaman dan homey. Tempat ini cocok untuk bersantai, mengobrol, maupun menikmati secangkir kopi di tengah suasana yang tenang.",
    address: "Jalan G. Batu Putih, Mangkura, Ujung Pandang, Makassar",
    category: "aesthetic",
    rating: 4.7,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/mark-trees-cafe.png",
    mapsLink: "https://maps.app.goo.gl/N8VvVz4BdFf2bM6EA",
    menu: ["Cafe Latte", "Cappuccino", "Americano", "Croffle", "Cheesecake", "Chicken Sandwich"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Work From Cafe", "Nongkrong", "Meeting santai", "Foto aesthetic"],
    favoriteSpot: "Area indoor dengan dominasi kayu hangat menjadi spot favorit untuk berfoto.",
    tips: "Datang pada pagi atau sore hari untuk menikmati suasana yang lebih tenang dan nyaman.",
    location: { lat: -5.1469113, lng: 119.4159946 }
  },
  {
    name: "Aynaka Coffee Racing Centre",
    description: "Cafe semi-outdoor dengan suasana hijau dipenuhi tanaman yang sejuk dan nyaman, cocok untuk ngopi, bersantai, atau mengerjakan tugas.",
    about: "Aynaka Coffee Racing Centre menghadirkan konsep semi-outdoor dengan suasana hijau yang dipenuhi tanaman sehingga terasa sejuk dan nyaman. Tempat ini cocok untuk menikmati kopi, bersantai bersama teman, maupun mengerjakan tugas di suasana yang tenang.",
    address: "Jalan Btn Gaedenia, Karampuang, Panakkukang, Makassar",
    category: "outdoor",
    rating: 4.5,
    priceRange: "$$",
    facilities: ["Outdoor Seating", "Indoor Seating", "WiFi", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/aynaka-coffee-racing-centre.png",
    mapsLink: "https://maps.app.goo.gl/eTQvkpYFTBk4Wt2b6",
    menu: ["Cafe Latte", "Cappuccino", "Es Kopi Susu", "Matcha Latte", "Chicken Wings", "Croffle"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Nongkrong", "Work From Cafe", "Quality Time", "Foto aesthetic"],
    favoriteSpot: "Area semi-outdoor dengan tanaman hijau menjadi spot favorit untuk bersantai dan berfoto.",
    tips: "Datang pada sore hari agar dapat menikmati udara yang lebih sejuk dan suasana yang nyaman.",
    location: { lat: -5.1458728, lng: 119.4502153 }
  },
  {
    name: "SIJA PETTARANI",
    description: "Cafe industrial modern dengan dominasi warna abu-abu yang bersih dan elegan, nyaman untuk bekerja, meeting, atau nongkrong santai.",
    about: "SIJA PETTARANI mengusung konsep industrial modern dengan dominasi warna abu-abu yang memberikan kesan bersih dan elegan. Tempatnya nyaman untuk bekerja, meeting ringan, maupun menikmati waktu santai bersama teman.",
    address: "Jl. Andi Pangeran Pettarani 3, Tamamaung, Panakkukang, Makassar",
    category: "aesthetic",
    rating: 4.8,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/sija-pettarani.png",
    mapsLink: "https://maps.app.goo.gl/MoZJk7KHMZEkJKwC7",
    menu: ["Signature Latte", "Americano", "Cappuccino", "Rice Bowl", "Croffle", "Toast"],
    priceInfo: "Rp20.000 – Rp60.000",
    suitableFor: ["Work From Cafe", "Meeting", "Nongkrong", "Foto aesthetic"],
    favoriteSpot: "Interior industrial modern dengan dominasi warna abu-abu menjadi spot favorit pengunjung.",
    tips: "Pilih tempat duduk dekat jendela untuk mendapatkan pencahayaan alami yang nyaman.",
    location: { lat: -5.1467249, lng: 119.4393314 }
  },
  {
    name: "Monochrome Cafe",
    description: "Cafe unik dengan perpaduan warna hitam-putih yang modern dan elegan, cocok untuk foto aesthetic, makan santai, dan nongkrong bersama teman.",
    about: "Monochrome Cafe memiliki konsep unik dengan perpaduan warna hitam dan putih yang memberikan kesan modern sekaligus elegan. Suasananya nyaman untuk menikmati kopi, makan bersama teman, maupun berburu foto estetik.",
    address: "Jalan Bulukunyi, Maricaya Baru, Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Dining Area", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/monochrome-cafe.png",
    mapsLink: "https://maps.app.goo.gl/pqokGk6spA9nc2rX9",
    menu: ["Cafe Latte", "Cappuccino", "Americano", "Pasta", "Chicken Katsu", "Cheesecake"],
    priceInfo: "Rp25.000 – Rp60.000",
    suitableFor: ["Nongkrong", "Foto aesthetic", "Makan santai", "Quality Time"],
    favoriteSpot: "Interior hitam-putih yang minimalis menjadi latar foto yang paling ikonik.",
    tips: "Datang pada siang hari agar pencahayaan alami membuat hasil foto semakin menarik.",
    location: { lat: -5.1471521, lng: 119.4216883 }
  },
  {
    name: "Crematology X Makassar",
    description: "Cafe modern di Phinisi Point dengan interior hangat dan area duduk cozy, cocok untuk ngopi santai setelah beraktivitas di kawasan Tanjung Bunga.",
    about: "Crematology X Makassar menawarkan suasana modern dengan interior yang hangat dan area duduk yang nyaman. Berlokasi di Phinisi Point, cafe ini cocok untuk menikmati kopi sambil bersantai setelah beraktivitas atau berjalan-jalan di kawasan Tanjung Bunga.",
    address: "Phinisi Point, Jalan Metro Tanjung Bunga, Lette, Mariso, Makassar",
    category: "aesthetic",
    rating: 4.5,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/crematology-x-makassar.png",
    mapsLink: "https://maps.app.goo.gl/teyyEnidH9w6HkNs6",
    menu: ["Flat White", "Cafe Latte", "Manual Brew", "Espresso", "Croissant", "Chocolate Cake"],
    priceInfo: "Rp25.000 – Rp65.000",
    suitableFor: ["Ngopi santai", "Meeting", "Quality Time", "Foto aesthetic"],
    favoriteSpot: "Area coffee bar dan interior modern menjadi spot favorit untuk berfoto.",
    tips: "Datang pada sore hari agar suasana lebih santai dan tidak terlalu ramai.",
    location: { lat: -5.1521777, lng: 119.4041426 }
  },
  {
    name: "STORIAMO COFFEE AND ROASTERY",
    description: "Cafe rindang dengan area indoor dan outdoor yang nyaman, cocok untuk bekerja, ngopi berkualitas, atau berkumpul bersama teman.",
    about: "STORIAMO COFFEE AND ROASTERY menghadirkan suasana rindang dengan area duduk yang nyaman, baik di dalam maupun luar ruangan. Tempat ini cocok untuk bekerja, menikmati kopi, maupun berkumpul bersama teman dalam suasana yang tenang.",
    address: "Topaz Lorong 2, Masale, Panakkukang, Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Seating", "WiFi", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/storiamo-coffe-and-roastery.png",
    mapsLink: "https://maps.app.goo.gl/2Tj3tikM2qViMKkv9",
    menu: ["Manual Brew", "Cafe Latte", "Cappuccino", "Es Kopi Susu", "Croffle", "Chicken Sandwich"],
    priceInfo: "Rp20.000 – Rp60.000",
    suitableFor: ["Work From Cafe", "Nongkrong", "Meeting santai", "Quality Time"],
    favoriteSpot: "Area outdoor yang rindang menjadi tempat favorit untuk bersantai dan berfoto.",
    tips: "Jika ingin suasana yang lebih tenang, datang pada pagi atau siang hari sebelum jam ramai.",
    location: { lat: -5.153884, lng: 119.4394774 }
  },
  {
    name: "Cafe Aestetic Dimakassar",
    description: "Cafe real dari link Google Maps yang kamu kirim. Konsepnya clean minimalis dengan area semi-outdoor, cocok untuk nongkrong malam, santai, dan foto aesthetic di area Manggala.",
    address: "Bitoa, Manggala, Makassar",
    category: "aesthetic",
    rating: 5.0,
    priceRange: "$$",
    facilities: ["Semi Outdoor", "Indoor Seating", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/cafe-aestetic-dimakassar.png",
    mapsLink: "https://maps.app.goo.gl/R66DTUCD6LNybUR99",
    location: { lat: -5.165512, lng: 119.4713769 }
  },
  {
    name: "Bangi Cafe Sunset CPI",
    description: "Cafe santai dengan pemandangan laut dan sunset yang indah di kawasan CPI, spot terbaik menikmati sore hari.",
    about: "Bangi Cafe Sunset CPI dikenal dengan suasananya yang santai dan pemandangan laut yang indah. Cafe ini menjadi pilihan tepat bagi pengunjung yang ingin menikmati sore sambil menyaksikan matahari terbenam di kawasan CPI.",
    address: "Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "outdoor",
    rating: 4.2,
    priceRange: "$$",
    facilities: ["Sea View", "Outdoor Seating", "Sunset Spot", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/bangi-cafe-sunset-cpi.png",
    mapsLink: "https://maps.app.goo.gl/faWz8Pj8EvjMR2EA8",
    menu: ["Americano", "Cafe Latte", "Teh Tarik", "Burger", "Kentang Goreng", "Roti Bakar"],
    priceInfo: "Rp20.000 – Rp60.000",
    suitableFor: ["Nongkrong sore", "Menikmati sunset", "Quality Time", "Foto aesthetic"],
    favoriteSpot: "Area sunset spot menjadi lokasi favorit pengunjung untuk berfoto.",
    tips: "Datang sekitar pukul 17.00 agar tidak kehabisan tempat di area outdoor.",
    location: { lat: -5.1498068, lng: 119.3940483 }
  },
  {
    name: "THE ICON BEACH LOUNGE & CAFE",
    description: "Beach lounge di tepi pantai CPI dengan area indoor dan outdoor yang luas, cocok menikmati angin laut sambil bersantai bersama keluarga.",
    about: "THE ICON BEACH LOUNGE & CAFE menawarkan suasana santai di tepi pantai dengan area indoor dan outdoor yang luas. Lokasinya sangat cocok untuk menikmati semilir angin laut sambil bersantai bersama keluarga maupun teman.",
    address: "Lego-Lego, Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "outdoor",
    rating: 4.6,
    priceRange: "$$$",
    facilities: ["Sea View", "Outdoor Seating", "Indoor Seating", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/the-icon-beach-lounge-cafe.png",
    mapsLink: "https://maps.app.goo.gl/EBfsuXrPBguUPEC28",
    menu: ["Cafe Latte", "Es Kopi Susu", "Pizza", "Seafood Platter", "Chicken Steak", "Mocktail"],
    priceInfo: "Rp30.000 – Rp90.000",
    suitableFor: ["Nongkrong", "Dinner", "Menikmati sunset", "Foto aesthetic"],
    favoriteSpot: "Area outdoor yang menghadap pantai menjadi tempat favorit untuk menikmati matahari terbenam.",
    tips: "Pilih tempat duduk di area luar saat sore agar mendapatkan pemandangan terbaik.",
    location: { lat: -5.147356, lng: 119.395425 }
  },
  {
    name: "Gravity Sky Lounge",
    description: "Sky lounge elegan di rooftop dengan panorama laut dari ketinggian, cocok untuk dinner romantis dan menikmati city light malam hari.",
    about: "Gravity Sky Lounge menghadirkan pengalaman bersantai di rooftop dengan panorama laut dari ketinggian. Suasana yang elegan dipadukan dengan pencahayaan malam menjadikannya tempat yang cocok untuk menikmati waktu bersama pasangan maupun teman.",
    address: "Swiss-BelHotel Makassar, Jalan Ujung Pandang 12, Bulogading, Ujung Pandang, Makassar",
    category: "rooftop",
    rating: 4.7,
    priceRange: "$$$",
    facilities: ["Sea View", "Indoor Seating", "Sky Lounge", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/gravity-sky-lounge.png",
    mapsLink: "https://maps.app.goo.gl/1dfn1A24eyuHxtrB8",
    menu: ["Signature Latte", "Cappuccino", "Mocktail", "Pasta", "Steak", "Dessert"],
    priceInfo: "Rp35.000 – Rp120.000",
    suitableFor: ["Dinner", "Quality Time", "Menikmati city light", "Foto malam"],
    favoriteSpot: "Area rooftop dengan latar laut dan lampu kota menjadi spot foto paling menarik.",
    tips: "Datang setelah matahari terbenam untuk menikmati pemandangan malam dari rooftop.",
    location: { lat: -5.136002, lng: 119.4043688 }
  },
  {
    name: "COASTLINE Cafe",
    description: "Cafe modern di tepi laut dengan area indoor dan outdoor yang nyaman, pemandangan laut dan angin sepoi-sepoi menjadikannya pilihan sempurna untuk bersantai.",
    about: "COASTLINE Cafe menawarkan suasana modern di tepi laut dengan area indoor dan outdoor yang nyaman. Pemandangan laut serta angin sepoi-sepoi menjadikan cafe ini pilihan tepat untuk bersantai, menikmati kopi, maupun berkumpul bersama teman.",
    address: "Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "outdoor",
    rating: 4.4,
    priceRange: "$$",
    facilities: ["Sea View", "Indoor Seating", "Outdoor Seating", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/coastline-cafe.png",
    mapsLink: "https://maps.app.goo.gl/YtmYUR94N4nBMWNW9",
    menu: ["Cafe Latte", "Americano", "Es Kopi Susu", "Fish & Chips", "Pizza", "Chicken Wings"],
    priceInfo: "Rp25.000 – Rp75.000",
    suitableFor: ["Nongkrong sore", "Menikmati sunset", "Quality Time", "Foto aesthetic"],
    favoriteSpot: "Area outdoor yang langsung menghadap laut menjadi spot terbaik untuk menikmati pemandangan.",
    tips: "Datang menjelang sore agar bisa menikmati sunset sambil menikmati kopi.",
    location: { lat: -5.148991, lng: 119.393503 }
  },
  {
    name: "Center Point Cafe",
    description: "Cafe di kawasan CPI dengan area terbuka menghadap laut, suasananya santai dan sejuk cocok untuk menikmati sore bersama teman atau keluarga.",
    about: "Center Point Cafe berada di kawasan Centre Point of Indonesia dengan area terbuka yang menghadap laut. Suasananya santai dan sejuk sehingga menjadi tempat yang ideal untuk menikmati sore sambil bersantai bersama teman atau keluarga.",
    address: "Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "outdoor",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Sea View", "Outdoor Seating", "Sunset Spot", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/center-point-cafe.png",
    mapsLink: "https://maps.app.goo.gl/5LJyqJ2YJcYLtDk47",
    menu: ["Americano", "Cafe Latte", "Es Kopi Susu", "Burger", "Kentang Goreng", "Chicken Wings"],
    priceInfo: "Rp25.000 – Rp70.000",
    suitableFor: ["Nongkrong sore", "Menikmati sunset", "Quality Time", "Foto aesthetic"],
    favoriteSpot: "Area outdoor yang menghadap laut menjadi tempat favorit untuk menikmati matahari terbenam.",
    tips: "Pilih tempat duduk di area luar sekitar satu jam sebelum matahari terbenam agar mendapatkan pemandangan terbaik.",
    location: { lat: -5.148242, lng: 119.3957857 }
  },
  {
    name: "Negeri Sembilan Melayu's Signature & Coffee",
    description: "Restoran & coffee shop elegan dengan nuansa Melayu modern, cocok untuk makan bersama keluarga atau menikmati kopi dalam suasana tenang.",
    about: "Negeri Sembilan Melayu's Signature & Coffee menggabungkan konsep restoran dan coffee shop dengan nuansa Melayu modern yang elegan. Tempatnya nyaman untuk makan bersama keluarga maupun menikmati kopi dalam suasana yang tenang.",
    address: "Lego-Lego, Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "aesthetic",
    rating: 4.9,
    priceRange: "$$$",
    facilities: ["Indoor Seating", "Dining Area", "AC", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/negeri-sembilan-signature-coffee.png",
    mapsLink: "https://maps.app.goo.gl/mMjNnEQy3NxNMrZE7",
    menu: ["Cafe Latte", "Teh Tarik", "Nasi Lemak", "Chicken Curry", "Roti Canai", "Dessert"],
    priceInfo: "Rp35.000 – Rp95.000",
    suitableFor: ["Makan bersama keluarga", "Meeting", "Quality Time", "Nongkrong santai"],
    favoriteSpot: "Interior bernuansa Melayu modern menjadi latar foto yang elegan.",
    tips: "Cocok dikunjungi saat jam makan siang atau makan malam bersama keluarga.",
    location: { lat: -5.1476032, lng: 119.3952551 }
  },
  {
    name: "Seroeni - Sunset Quay",
    description: "Cafe dengan pemandangan laut yang indah, area indoor dan outdoor nyaman, cocok untuk menikmati kopi sambil menyaksikan matahari terbenam.",
    about: "Seroeni - Sunset Quay menawarkan pengalaman bersantai dengan pemandangan laut yang indah. Area indoor dan outdoor yang nyaman menjadikan cafe ini cocok untuk menikmati makanan, kopi, maupun momen matahari terbenam bersama keluarga atau teman.",
    address: "Lego-Lego, Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "outdoor",
    rating: 4.9,
    priceRange: "$$$",
    facilities: ["Sea View", "Outdoor Seating", "Indoor Seating", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/seroeni-sunset-quay.png",
    mapsLink: "https://maps.app.goo.gl/aQ6iWB97u3cEhgB87",
    menu: ["Cafe Latte", "Es Kopi Susu", "Nasi Goreng", "Seafood Rice Bowl", "Pasta", "Dessert"],
    priceInfo: "Rp35.000 – Rp90.000",
    suitableFor: ["Dinner", "Quality Time", "Menikmati sunset", "Foto aesthetic"],
    favoriteSpot: "Area outdoor yang langsung menghadap laut menjadi spot paling diminati.",
    tips: "Datang sekitar pukul 17.00 untuk mendapatkan pemandangan sunset terbaik.",
    location: { lat: -5.1470229, lng: 119.3959728 }
  },
  {
    name: "Ballairate",
    description: "Cafe lounge modern di area hotel, interiornya bersih dan elegan cocok untuk meeting, kerja, atau bersantai di tengah kota.",
    about: "Ballairate menawarkan suasana tenang dengan konsep lounge modern yang berada di area hotel. Interiornya bersih, nyaman, dan elegan sehingga cocok untuk meeting, menikmati kopi, atau bersantai di tengah kota.",
    address: "Swiss-BelHotel Makassar, Jalan Ujung Pandang 12, Bulogading, Ujung Pandang, Makassar",
    category: "aesthetic",
    rating: 4.4,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/ballairate.png",
    mapsLink: "https://maps.app.goo.gl/Xpng9ALfLSo7J6HS7",
    menu: ["Espresso", "Cafe Latte", "Cappuccino", "Club Sandwich", "Pasta", "Cake"],
    priceInfo: "Rp30.000 – Rp80.000",
    suitableFor: ["Meeting", "Kerja", "Quality Time", "Nongkrong santai"],
    favoriteSpot: "Area lounge dengan interior modern menjadi spot favorit untuk berfoto.",
    tips: "Jika ingin suasana yang tenang, datang pada pagi atau siang hari.",
    location: { lat: -5.1365371, lng: 119.4037076 }
  },
  {
    name: "Kultur Haus Sunset Quay",
    description: "Cafe modern dengan perpaduan elemen kayu dan tanaman hijau di kawasan Sunset Quay CPI, pilihan tepat untuk ngopi sambil menikmati suasana tepi laut.",
    about: "Kultur Haus Sunset Quay menghadirkan suasana modern dengan perpaduan elemen kayu dan tanaman hijau yang memberikan kesan hangat sekaligus elegan. Berlokasi di kawasan Sunset Quay CPI, cafe ini menjadi pilihan tepat untuk menikmati kopi sambil bersantai dengan suasana tepi laut.",
    address: "Lego-Lego, Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/kultur-haus-sunset-quay.png",
    mapsLink: "https://maps.app.goo.gl/xNa1NUXsFRfGJuAu6",
    menu: ["Cafe Latte", "Cappuccino", "Matcha Latte", "Croissant", "Chicken Sandwich", "Cheesecake"],
    priceInfo: "Rp30.000 – Rp75.000",
    suitableFor: ["Quality Time", "Meeting santai", "Foto aesthetic", "Nongkrong"],
    favoriteSpot: "Area dekat jendela dengan pemandangan Sunset Quay menjadi tempat favorit untuk berfoto.",
    tips: "Datang menjelang sore agar dapat menikmati suasana sunset setelah menikmati kopi.",
    location: { lat: -5.1473483, lng: 119.3956325 }
  },
  {
    name: "Fore Coffee - Sunset Quay",
    description: "Cafe modern khas Fore dengan lokasi strategis di kawasan Sunset Quay CPI, suasana bersih dan cocok untuk ngopi sambil menikmati area tepi laut.",
    about: "Fore Coffee - Sunset Quay menghadirkan konsep modern khas Fore dengan lokasi strategis di kawasan Sunset Quay, CPI. Suasananya bersih, nyaman, dan cocok untuk menikmati kopi sambil bersantai atau melihat aktivitas di sekitar kawasan tepi laut.",
    address: "Centre Point of Indonesia (CPI), Panambungan, Mariso, Makassar",
    category: "aesthetic",
    rating: 4.2,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/fore-coffee-sunset-quay.png",
    mapsLink: "https://maps.app.goo.gl/QfxFZk9LtekmsYRt8",
    menu: ["Butterscotch Sea Salt Latte", "Aren Latte", "Americano", "Matcha Latte", "Butter Croissant", "Cookies"],
    priceInfo: "Rp25.000 – Rp60.000",
    suitableFor: ["Nongkrong", "Work From Cafe", "Ngopi cepat", "Foto aesthetic"],
    favoriteSpot: "Area depan cafe dengan latar kawasan Sunset Quay menjadi spot favorit pengunjung.",
    tips: "Datang menjelang sore agar setelah menikmati kopi, kamu juga bisa berjalan santai di area CPI dan menikmati suasana matahari terbenam.",
    location: { lat: -5.1489976, lng: 119.3934978 }
  },
  {
    name: "Wam's Coffee",
    description: "Cafe industrial hangat dengan area duduk yang nyaman untuk bersantai maupun bekerja, suasananya tenang cocok untuk ngopi sambil mengerjakan tugas.",
    about: "Wam's Coffee menawarkan konsep industrial hangat dengan area duduk yang nyaman untuk bersantai maupun bekerja. Suasananya tenang sehingga cocok untuk menikmati kopi sambil mengerjakan tugas atau berbincang bersama teman.",
    address: "Jalan Inspeksi Kanal Puri Borong Raya, Borong, Manggala, Makassar",
    category: "aesthetic",
    rating: 4.9,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Seating", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/wams-coffee.png",
    mapsLink: "https://maps.app.goo.gl/VzEJ1wFr869z2vts9",
    menu: ["Cafe Latte", "Cappuccino", "Americano", "Es Kopi Susu", "Rice Bowl", "Croffle"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Work From Cafe", "Nongkrong", "Belajar", "Quality Time"],
    favoriteSpot: "Area indoor bernuansa industrial menjadi tempat favorit untuk berfoto.",
    tips: "Datang pada sore hari agar suasana lebih santai dan tidak terlalu ramai.",
    location: { lat: -5.1657571, lng: 119.4664693 }
  },
  {
    name: "Utata Space",
    description: "Cafe industrial modern dengan workspace luas, cocok untuk Work From Cafe, belajar, meeting, dan nongkrong santai.",
    about: "Utata Space mengusung konsep industrial modern dengan area yang luas dan nyaman. Tersedia ruang kerja yang mendukung aktivitas belajar maupun Work From Cafe, sekaligus menghadirkan suasana santai untuk berkumpul bersama teman.",
    address: "Bitoa, Manggala, Makassar",
    category: "aesthetic",
    rating: 4.4,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Workspace", "WiFi", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/utata-space.png",
    mapsLink: "https://maps.app.goo.gl/EfyNNJuhDpHZWMmQ6",
    menu: ["Cafe Latte", "Matcha Latte", "Americano", "Rice Bowl", "Croffle", "Chicken Popcorn"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Work From Cafe", "Belajar", "Meeting", "Nongkrong"],
    favoriteSpot: "Area workspace dan interior industrial menjadi spot favorit untuk bekerja sekaligus berfoto.",
    tips: "Bawa laptop dan datang pada pagi atau siang hari agar mendapatkan suasana kerja yang lebih nyaman.",
    location: { lat: -5.1684049, lng: 119.4682915 }
  },
  {
    name: "Warkop Phoenam",
    description: "Warkop legendaris Makassar sejak 1946. Kopi tubruk khas Makassar dan roti bakar ikon kuliner kota.",
    about: "Warkop Phoenam merupakan salah satu warkop legendaris di Makassar yang telah dikenal sejak tahun 1946. Tempat ini terkenal dengan kopi tubruk khas Makassar dan roti bakarnya yang menjadi favorit banyak pengunjung dari berbagai kalangan.",
    address: "Jl. Sulawesi No. 14, Makassar",
    category: "traditional",
    rating: 4.6,
    priceRange: "$",
    facilities: ["Outdoor Seating", "Traditional Coffee", "Parking", "24 Jam"],
    openHours: "24 Jam",
    image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600&h=400&fit=crop",
    menu: ["Kopi Tubruk", "Kopi Susu", "Teh Tarik", "Roti Bakar", "Pisang Goreng", "Indomie"],
    priceInfo: "Rp15.000 – Rp40.000",
    suitableFor: ["Ngopi tradisional", "Nongkrong malam", "Kuliner khas Makassar", "Berkumpul bersama teman"],
    favoriteSpot: "Area depan warkop dengan suasana khas Makassar menjadi daya tarik tersendiri.",
    tips: "Datang pada malam hari untuk merasakan suasana khas warkop yang ramai dan hidup.",
    location: { lat: -5.1380, lng: 119.4100 }
  },
  {
    name: "Beyours Coffee & Space",
    description: "Cafe dengan interior kayu yang hangat dan cozy, cocok untuk ngopi santai dan nongkrong dengan nuansa rustic yang nyaman.",
    about: "Beyours Coffee & Space menghadirkan suasana hangat melalui dominasi interior kayu bergaya rustic. Tempatnya nyaman untuk menikmati kopi, bekerja, maupun menghabiskan waktu bersama teman dan keluarga.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.5,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/beyours-coffee-space.png",
    mapsLink: "https://maps.app.goo.gl/ncXZq8ZXQ6D5TrAq6",
    menu: ["Signature Latte", "Cappuccino", "Americano", "Matcha Latte", "Croffle", "Brownies"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Work From Cafe", "Nongkrong", "Meeting santai", "Quality Time"],
    favoriteSpot: "Interior kayu bergaya rustic menjadi latar favorit untuk berfoto.",
    tips: "Pilih tempat duduk di dekat jendela agar mendapatkan pencahayaan alami yang nyaman.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "REAL CAFE",
    description: "Cafe dengan konsep industrial yang unik dan autentik, cocok untuk nongkrong malam dengan suasana yang berbeda dan raw.",
    about: "REAL CAFE mengusung konsep industrial dengan desain yang sederhana namun tetap modern. Perpaduan area indoor dan outdoor menciptakan suasana santai yang cocok untuk menikmati kopi, mengobrol bersama teman, maupun melepas penat setelah beraktivitas.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Seating", "WiFi", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/real-cafe.png",
    mapsLink: "https://maps.app.goo.gl/g3dNnR2c69Zw5oLk8",
    menu: ["Cafe Latte", "Americano", "Es Kopi Susu", "Chicken Wings", "Kentang Goreng", "Toast"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Nongkrong", "Quality Time", "Foto aesthetic", "Santai setelah bekerja"],
    favoriteSpot: "Area outdoor dengan nuansa industrial menjadi spot favorit untuk bersantai dan berfoto.",
    tips: "Datang pada sore menjelang malam untuk menikmati suasana yang lebih nyaman.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "KOPIKU",
    description: "Cafe kopi dengan neon sign khas yang ikonik, cocok untuk nongkrong malam dengan suasana casual dan ramai.",
    about: "KOPIKU dikenal dengan suasana kasual yang selalu ramai dikunjungi. Neon sign khas dan konsep sederhana membuat cafe ini nyaman untuk nongkrong malam sambil menikmati berbagai pilihan kopi.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.9,
    priceRange: "$",
    facilities: ["Indoor Seating", "Outdoor Seating", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/kopiku.jpg",
    mapsLink: "https://maps.app.goo.gl/JG3nB6FziCDu8dzZ9",
    menu: ["Es Kopi Susu KOPIKU", "Cafe Latte", "Cappuccino", "Americano", "Pisang Goreng", "Toast"],
    priceInfo: "Rp18.000 – Rp45.000",
    suitableFor: ["Nongkrong malam", "Quality Time", "Ngopi santai", "Berkumpul bersama teman"],
    favoriteSpot: "Neon sign khas KOPIKU menjadi ikon utama untuk berfoto.",
    tips: "Datang lebih awal pada malam hari karena cafe ini sering dipadati pengunjung.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "THEMA",
    description: "Cafe modern dengan interior industrial minimalis, dilengkapi TV layar besar, cocok untuk nongkrong santai sambil nonton atau kerja.",
    about: "THEMA memiliki konsep industrial minimalis dengan ruangan yang luas dan nyaman. Dilengkapi TV layar besar serta fasilitas WiFi, cafe ini cocok sebagai tempat berkumpul, bekerja, maupun menikmati pertandingan bersama teman.",
    address: "Makassar",
    category: "coworking",
    rating: 4.7,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "WiFi", "TV Layar Besar", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/thema.jpg",
    mapsLink: "https://maps.app.goo.gl/rZ2PwgNQ7KYBbA57A",
    menu: ["Cappuccino", "Cafe Latte", "Americano", "Rice Bowl", "Chicken Wings", "Toast"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Work From Cafe", "Nobar", "Nongkrong", "Meeting"],
    favoriteSpot: "Area tengah cafe dengan desain industrial menjadi sudut favorit untuk berfoto.",
    tips: "Jika ingin suasana lebih tenang untuk bekerja, datang pada siang hari.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "TOMORO COFFEE",
    description: "Cafe kopi chain modern dengan konsep clean dan minimalis, cocok untuk ngopi cepat, kerja, dan nongkrong santai dengan kopi berkualitas.",
    about: "TOMORO COFFEE menawarkan konsep modern dan minimalis yang identik dengan coffee chain masa kini. Tempatnya nyaman untuk menikmati kopi berkualitas, bekerja singkat, maupun sekadar bersantai di tengah aktivitas.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.9,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Stop Kontak"],
    openHours: "Cek jam buka di Google Maps",
    image: "/tomoro-coffee.jpg",
    mapsLink: "https://maps.app.goo.gl/XnqvaoTVWZwQJtaXA",
    menu: ["TOMORO Latte", "Americano", "Oat Latte", "Matcha Latte", "Butter Croissant", "Cookies"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Work From Cafe", "Meeting singkat", "Ngopi cepat", "Belajar"],
    favoriteSpot: "Area coffee bar dan interior minimalis menjadi spot foto yang bersih dan modern.",
    tips: "Datang pada pagi hari untuk suasana yang lebih tenang jika ingin bekerja.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Eksposed 3.0 Signature Pettarani",
    description: "Cafe modern dua lantai dengan konsep industrial dan rooftop terbuka, cocok untuk nongkrong, foto aesthetic, dan menikmati suasana sore di area Pettarani.",
    about: "Eksposed 3.0 Signature Pettarani merupakan cafe dua lantai dengan konsep industrial modern yang dilengkapi area rooftop terbuka. Suasananya nyaman untuk menikmati waktu santai sambil melihat pemandangan sekitar, terutama saat sore hingga malam hari.",
    address: "Jalan A.P. Pettarani, Makassar",
    category: "rooftop",
    rating: 4.5,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Rooftop", "AC", "WiFi", "Coffee Bar", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/eksposed-pettarani.jpg",
    mapsLink: "https://maps.app.goo.gl/7SownMCEJPrFx36U8",
    menu: ["Cafe Latte", "Americano", "Es Kopi Susu", "Chicken Rice Bowl", "Pasta", "French Fries"],
    priceInfo: "Rp25.000 – Rp65.000",
    suitableFor: ["Nongkrong sore", "Menikmati sunset", "Foto aesthetic", "Meeting santai"],
    favoriteSpot: "Area rooftop menjadi spot terbaik untuk menikmati pemandangan dan berfoto saat matahari terbenam.",
    tips: "Datang sekitar pukul 17.00 agar bisa menikmati suasana sore sekaligus malam.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "VENDOR COFFEE",
    description: "Cafe aesthetic dengan interior kayu hangat dan neon sign elegan, cocok untuk ngopi santai dan foto aesthetic.",
    about: "VENDOR COFFEE menghadirkan suasana hangat melalui interior kayu dan pencahayaan yang nyaman. Konsepnya sederhana namun tetap modern, menjadikannya tempat yang pas untuk menikmati kopi sambil bersantai.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.8,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/vendor-coffee.jpg",
    mapsLink: "https://maps.app.goo.gl/KXnTFVFziugUWwxy9",
    menu: ["Signature Latte", "Cappuccino", "Americano", "Es Kopi Susu", "Toast", "Brownies"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Nongkrong", "Kerja ringan", "Foto aesthetic", "Quality Time"],
    favoriteSpot: "Area coffee bar dan interior kayu dengan neon sign menjadi spot foto yang paling menarik.",
    tips: "Jika ingin suasana lebih tenang, datang pada pagi atau siang hari sebelum jam ramai.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Monolith Coffee",
    description: "Cafe dengan arsitektur unik bergaya heritage, cocok untuk ngopi santai dan foto aesthetic dengan nuansa kolonial yang elegan.",
    about: "Monolith Coffee memiliki arsitektur bergaya heritage yang memberikan nuansa klasik dan elegan. Perpaduan bangunan bersejarah dengan konsep coffee shop modern menjadikan cafe ini menarik bagi pecinta kopi maupun fotografi.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.7,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/monolith-coffee.jpg",
    mapsLink: "https://maps.app.goo.gl/TibXk1eQnwWsu1XR7",
    menu: ["Manual Brew", "Flat White", "Cafe Latte", "Espresso", "Croissant", "Cheesecake"],
    priceInfo: "Rp25.000 – Rp60.000",
    suitableFor: ["Foto aesthetic", "Nongkrong", "Quality Time", "Menikmati kopi"],
    favoriteSpot: "Bagian depan bangunan heritage dan area coffee bar menjadi spot foto yang paling diminati.",
    tips: "Datang pada pagi atau sore hari agar bisa menikmati keindahan arsitektur dengan pencahayaan alami.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Aksen Cafe",
    description: "Cafe Coffee & Eatery dengan konsep bersih dan minimalis, cocok untuk ngopi santai dan makan ringan di suasana yang nyaman.",
    about: "Aksen Cafe mengusung konsep coffee & eatery dengan desain minimalis yang bersih dan nyaman. Tempatnya cocok untuk menikmati kopi, makan bersama keluarga, maupun berkumpul dengan teman dalam suasana santai.",
    address: "Makassar",
    category: "aesthetic",
    rating: 5.0,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Seating", "AC", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/aksen-cafe.jpg",
    mapsLink: "https://maps.app.goo.gl/JrFe2oAb2oLBb1sG8",
    menu: ["Cafe Latte", "Cappuccino", "Es Kopi Susu", "Nasi Goreng", "Chicken Katsu", "Spaghetti"],
    priceInfo: "Rp20.000 – Rp60.000",
    suitableFor: ["Makan bersama", "Nongkrong", "Meeting santai", "Kerja ringan"],
    favoriteSpot: "Area indoor dengan desain minimalis dan pencahayaan hangat menjadi tempat favorit untuk berfoto.",
    tips: "Cocok dikunjungi saat jam makan siang maupun sore hari karena suasananya lebih santai.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "MAUKI",
    description: "Cafe malam dengan bangunan dua lantai megah, lampu string yang hangat, dan nuansa industrial modern. Cocok untuk nongkrong malam dan foto aesthetic.",
    about: "MAUKI menawarkan konsep industrial modern dengan bangunan dua lantai serta area indoor dan outdoor yang luas. Lampu-lampu gantung menciptakan suasana hangat sehingga nyaman untuk nongkrong hingga larut malam.",
    address: "Makassar",
    category: "outdoor",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "Outdoor Seating", "AC", "Coffee Bar", "WiFi", "Parking", "Smoking Area"],
    openHours: "Cek jam buka di Google Maps",
    image: "/mauki.jpg",
    mapsLink: "https://maps.app.goo.gl/Dh95SiFuaiqLLQCf9",
    menu: ["Cafe Latte", "Cappuccino", "Matcha Latte", "Rice Bowl", "Pasta", "Chicken Wings"],
    priceInfo: "Rp25.000 – Rp65.000",
    suitableFor: ["Nongkrong malam", "Gathering", "Quality Time", "Foto aesthetic"],
    favoriteSpot: "Area outdoor dengan lampu gantung dan bangunan dua lantai menjadi spot foto favorit.",
    tips: "Datang setelah pukul 18.00 untuk menikmati suasana malam yang lebih hidup.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Obladi Cafe",
    description: "Cafe industrial dengan dominasi bata merah dan pencahayaan hangat, tempat yang luas cocok untuk bekerja, berdiskusi, maupun berkumpul.",
    about: "Obladi Cafe memiliki konsep industrial dengan dominasi bata merah dan pencahayaan hangat yang memberikan suasana nyaman. Tempatnya luas sehingga cocok untuk bekerja, berdiskusi, maupun berkumpul bersama teman.",
    address: "Makassar",
    category: "cozy",
    rating: 4.7,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "WiFi", "Coffee Bar", "Stop Kontak", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/obladi-cafe.jpg",
    mapsLink: "https://maps.app.goo.gl/dn1oS9cdeN5KR4hX6",
    menu: ["Cappuccino", "Americano", "Es Kopi Susu", "Rice Bowl", "Chicken Wings", "Croffle"],
    priceInfo: "Rp20.000 – Rp60.000",
    suitableFor: ["Work From Cafe", "Meeting", "Belajar", "Nongkrong"],
    favoriteSpot: "Dinding bata ekspos dan area coffee bar menjadi latar foto yang menarik.",
    tips: "Bawalah laptop jika ingin bekerja karena tersedia fasilitas yang mendukung.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Bring.In Cafe",
    description: "Cafe dengan interior kayu hangat dan plafon kisi-kisi estetik, cocok untuk nongkrong malam dan foto aesthetic.",
    about: "Bring.In Cafe menghadirkan suasana hangat dengan interior kayu dan plafon bergaya modern. Tempat ini nyaman untuk bersantai sambil menikmati kopi, baik di siang maupun malam hari.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/bringin-cafe.jpg",
    mapsLink: "https://maps.app.goo.gl/crK96ybdS1Trz58D8",
    menu: ["Cafe Latte", "Cappuccino", "Mocha", "Es Kopi Susu", "Toast", "French Fries"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Nongkrong", "Quality Time", "Foto aesthetic", "Kerja ringan"],
    favoriteSpot: "Plafon kayu dan area duduk dekat coffee bar menjadi sudut foto yang paling menarik.",
    tips: "Waktu terbaik berkunjung adalah menjelang malam saat suasana cafe lebih hidup.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "AnHour Coffee House",
    description: "Cafe industrial dengan dinding semen ekspos dan bar bata merah yang ikonik, cocok untuk ngopi santai dan foto aesthetic.",
    about: "AnHour Coffee House mengusung konsep industrial dengan dinding semen ekspos dan bar bata merah yang menjadi ciri khasnya. Suasananya nyaman dan cocok untuk menikmati kopi sambil bersantai atau berbincang dengan teman.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/anhour-coffee-house.jpg",
    mapsLink: "https://maps.app.goo.gl/6fTJWFT53fhhKY266",
    menu: ["Espresso", "Cafe Latte", "Flat White", "V60", "Croissant", "Chicken Popcorn"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Ngopi santai", "Nongkrong", "Foto aesthetic", "Meeting ringan"],
    favoriteSpot: "Area bar bata merah dan interior industrial menjadi spot favorit pengunjung untuk berfoto.",
    tips: "Pilih tempat duduk di dekat area bar untuk menikmati suasana cafe yang lebih khas.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Heaven With You",
    description: "Cafe minimalis modern serba putih dengan sofa velvet dan dekorasi bunga kering, suasananya romantic dan sangat cocok untuk foto aesthetic.",
    about: "Heaven With You menghadirkan konsep minimalis modern dengan dominasi warna putih yang memberikan kesan bersih, elegan, dan menenangkan. Dipadukan dengan sofa velvet serta dekorasi bunga kering, cafe ini menjadi pilihan tepat untuk bersantai maupun mengabadikan momen bersama teman atau pasangan.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/heaven-with-you.jpg",
    mapsLink: "https://maps.app.goo.gl/uSfDLaaLaB4t52Jx9",
    menu: ["Signature Latte", "Vanilla Latte", "Matcha Latte", "Chocolate Drink", "Cheesecake", "Croffle"],
    priceInfo: "Rp25.000 – Rp60.000",
    suitableFor: ["Quality Time", "Kencan", "Nongkrong santai", "Foto aesthetic"],
    favoriteSpot: "Area sofa putih dengan dekorasi bunga kering menjadi spot foto yang paling diminati.",
    tips: "Datang pada siang hari untuk mendapatkan pencahayaan alami yang membuat hasil foto semakin menarik.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Soraa Cafe",
    description: "Cafe cozy dengan suasana hangat, rak display estetik, dan ruangan ber-AC yang nyaman. Cocok untuk nongkrong santai bersama teman-teman.",
    about: "Soraa Cafe menawarkan suasana hangat dan nyaman dengan interior yang didominasi rak display estetik dan area duduk yang rapi. Tempat ini cocok untuk menikmati kopi sambil berbincang santai atau menghabiskan waktu bersama keluarga dan teman.",
    address: "Makassar",
    category: "cozy",
    rating: 5.0,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/soraa-cafe.jpg",
    mapsLink: "https://maps.app.goo.gl/9p681wuZaLNjGP1Z7",
    menu: ["Cafe Latte", "Cappuccino", "Americano", "Es Kopi Susu", "Brownies", "Toast"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Nongkrong", "Belajar", "Kerja ringan", "Quality Time"],
    favoriteSpot: "Rak display dan sudut interior bernuansa hangat menjadi latar foto yang estetik.",
    tips: "Datang pada sore hari untuk menikmati suasana yang lebih tenang dan nyaman.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Temu Kopi",
    description: "Cafe modern dengan interior abu-abu elegan, sofa nyaman, dan bar kopi lengkap. Tempat yang sempurna untuk bersantai sambil menikmati kopi berkualitas.",
    about: "Temu Kopi memiliki desain modern dengan perpaduan warna abu-abu yang elegan serta area duduk yang nyaman. Cafe ini menawarkan suasana santai yang cocok untuk bekerja, meeting, maupun menikmati kopi berkualitas bersama teman.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.9,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Stop Kontak", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/temu-kopi.jpg",
    mapsLink: "https://maps.app.goo.gl/HqoYPpLpuqgqJVMT9",
    menu: ["Manual Brew", "Cappuccino", "Cafe Latte", "Es Kopi Susu", "Croissant", "Chicken Sandwich"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Work From Cafe", "Meeting", "Nongkrong", "Foto aesthetic"],
    favoriteSpot: "Area coffee bar dan sofa modern menjadi tempat favorit pengunjung untuk berfoto.",
    tips: "Jika ingin suasana lebih tenang untuk bekerja, datang pada pagi atau siang hari.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "VAAN IN SKY",
    description: "Cafe outdoor dengan konsep gedung tua bersejarah dan neon sign ikonik. Suasana malam yang unik dan ramai, cocok untuk nongkrong seru bersama teman.",
    about: "VAAN IN SKY menawarkan konsep outdoor dengan nuansa bangunan bergaya klasik yang dipadukan lampu-lampu hangat di malam hari. Suasananya ramai dan cocok untuk menikmati malam bersama teman sambil menikmati udara terbuka.",
    address: "Makassar",
    category: "outdoor",
    rating: 3.8,
    priceRange: "$",
    facilities: ["Outdoor Seating", "Live Music", "Parking", "Smoking Area"],
    openHours: "Cek jam buka di Google Maps",
    image: "/vaan-in-sky.jpg",
    mapsLink: "https://maps.app.goo.gl/W81VVJewTd2WbJ9A7",
    menu: ["Es Kopi Susu", "Americano", "Cappuccino", "Milkshake", "Pizza", "Kentang Goreng"],
    priceInfo: "Rp20.000 – Rp60.000",
    suitableFor: ["Nongkrong malam", "Berkumpul bersama teman", "Menikmati live music", "Foto malam"],
    favoriteSpot: "Area outdoor dengan lampu gantung dan bangunan bergaya klasik menjadi spot foto yang paling menarik.",
    tips: "Datang menjelang matahari terbenam agar bisa menikmati suasana sore hingga malam sekaligus mendapatkan spot duduk terbaik.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Nuiz Coffee",
    description: "Cafe kekinian dengan fasad beton estetik, neon sign modern, dan pohon palem di entrance yang memukau. Perfect untuk foto malam hari dan ngopi santai.",
    about: "Nuiz Coffee hadir dengan konsep modern yang dipadukan sentuhan industrial. Fasad beton, neon sign, dan area masuk yang dihiasi pohon palem memberikan kesan estetik sejak pertama kali datang. Tempat ini cocok untuk menikmati kopi sambil bersantai atau berkumpul bersama teman.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/nuiz-coffee.jpg",
    mapsLink: "https://maps.app.goo.gl/cnJtL72f6wzPSaxF6",
    menu: ["Cafe Latte", "Caramel Latte", "Americano", "Es Kopi Susu", "Croffle", "Chicken Popcorn"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Nongkrong", "Foto aesthetic", "Kerja ringan", "Quality Time"],
    favoriteSpot: "Fasad depan dengan pohon palem dan neon sign menjadi spot foto yang paling ikonik.",
    tips: "Datang menjelang malam untuk menikmati pencahayaan cafe yang lebih estetik.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "BW Coffee Daya",
    description: "Cafe modern minimalis dengan interior kayu elegan, partisi kaca hitam estetik, dan konsep coffee plus barbershop yang unik di area Daya.",
    about: "BW Coffee Daya menawarkan konsep modern minimalis dengan sentuhan interior kayu yang elegan. Keunikan cafe ini terletak pada konsep coffee shop yang dipadukan dengan barbershop, sehingga memberikan pengalaman nongkrong yang berbeda dan menarik.",
    address: "Daya, Makassar",
    category: "aesthetic",
    rating: 4.9,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/bw-coffee-daya.jpg",
    mapsLink: "https://maps.app.goo.gl/GNpHC5Ua7BWxvAiH7",
    menu: ["Cafe Latte", "Es Kopi Susu", "Caramel Macchiato", "Matcha Latte", "Chicken Katsu", "Kentang Goreng"],
    priceInfo: "Rp20.000 – Rp55.000",
    suitableFor: ["Nongkrong", "Meeting santai", "Menunggu sambil menikmati kopi", "Foto aesthetic"],
    favoriteSpot: "Area coffee bar dan interior kayu modern menjadi spot favorit untuk berfoto.",
    tips: "Datang pada sore hari agar suasana lebih nyaman dan tidak terlalu ramai.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Sekan Coffee (Racing Centre)",
    description: "Cafe retro hangat dengan rak vinyl record ikonik, sofa kulit, dan dekorasi kayu kental nuansa 70an. Cocok untuk ngopi santai sambil menikmati musik.",
    address: "Racing Centre, Makassar",
    category: "cozy",
    rating: 4.5,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Music"],
    openHours: "Cek jam buka di Google Maps",
    image: "/sekan-coffee.jpg",
    mapsLink: "https://maps.app.goo.gl/rUY9SNw4XeKFx2ge8",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Povibes",
    description: "Cafe kekinian dengan neon sign bubble yang cute, dominasi warna hijau dan krem yang segar. Cocok untuk anak muda yang suka vibe aesthetic dan playful.",
    about: "Povibes menghadirkan konsep cafe kekinian dengan perpaduan warna hijau dan krem yang memberikan kesan segar dan nyaman. Suasananya santai dengan dekorasi modern sehingga cocok untuk nongkrong, mengobrol, maupun mengabadikan momen bersama teman.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.8,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/povibes.jpg",
    mapsLink: "https://maps.app.goo.gl/qYezLxQb3itpDxpM6",
    menu: ["Es Kopi Susu", "Matcha Latte", "Vanilla Latte", "Chocolate Drink", "Chicken Wings", "Kentang Goreng"],
    priceInfo: "Rp20.000 – Rp45.000",
    suitableFor: ["Nongkrong", "Foto aesthetic", "Quality time", "Kerja ringan"],
    favoriteSpot: "Neon sign dan sudut interior bernuansa hijau menjadi spot yang paling menarik untuk berfoto.",
    tips: "Jika ingin suasana yang lebih tenang, datang pada pagi atau siang hari. Untuk foto dengan pencahayaan alami, pilih tempat duduk di dekat jendela.",
    location: { lat: -5.1500, lng: 119.4300 }
  },
  {
    name: "Camell Coffee",
    description: "Cafe modern dengan fasad kaca melengkung dan neon sign putih elegan. Interior hangat dengan bar kayu yang cozy, sempurna untuk ngopi malam hari.",
    about: "Camell Coffee merupakan cafe modern dengan konsep minimalis yang mengutamakan kenyamanan pengunjung. Interior didominasi material kayu, pencahayaan hangat, dan desain yang estetik sehingga cocok untuk bersantai, mengerjakan tugas, maupun menikmati secangkir kopi bersama teman.",
    address: "Makassar",
    category: "aesthetic",
    rating: 4.6,
    priceRange: "$$",
    facilities: ["Indoor Seating", "AC", "Coffee Bar", "WiFi", "Stop Kontak", "Parking"],
    openHours: "Cek jam buka di Google Maps",
    image: "/camell-coffee.jpg",
    mapsLink: "https://maps.app.goo.gl/ooy6KDAXxUJpB3Dx6",
    menu: ["Es Kopi Susu Camell", "Cappuccino", "Cafe Latte", "Americano", "Croissant", "French Fries"],
    priceInfo: "Rp20.000 – Rp50.000",
    suitableFor: ["Work From Cafe (WFC)", "Nongkrong bersama teman", "Meeting santai", "Foto aesthetic"],
    favoriteSpot: "Area coffee bar dan fasad kaca melengkung menjadi spot foto favorit karena tampil modern dengan pencahayaan yang menarik.",
    tips: "Datang pada sore hingga malam hari untuk menikmati suasana yang lebih hangat dan pencahayaan yang cocok untuk berfoto.",
    location: { lat: -5.1500, lng: 119.4300 }
  }
].map(cafe => ({
  ...cafe,
  image: resolveStoredImageUrl(cafe.image),
}));

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/cafe_makassar');
    console.log('Connected to MongoDB');
    
    await Cafe.deleteMany({});
    console.log('Cleared existing cafes');
    
    await Cafe.insertMany(cafes);
    console.log(`✅ Seeded ${cafes.length} cafes`);
    
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seedDB();
